services:
  app:
    # Verwendet das eigene Node.js-Image
    image: my-node-app
    # Bindet den Port 3000 des Containers auf den Port 13000 des Hosts
    ports:
      - "14000:3000"
    # Bindet das aktuelle Verzeichnis auf /usr/src/app im Container
    volumes:
      - .:/usr/src/app
    # Definiert die Umgebungsvariablen
    environment:
      - NODE_ENV=development
    # Definiert, dass der Container immer neu gestartet wird
    restart: always
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8080:80"